### ISSUE TITLE
"An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception."

### ISSUE THREAD

**Issue by shubhm-agrwl** [vert-x3/vertx-mqtt#136]
When I am starting 20 new Vertx instances to start 20 MQTT Brokers, I am getting an error in one of the mqtt brokers and is not able to initiate.

Code to start 20 instances:

         cluster.result().deployVerticle(
              "com.abc.abc",
              new DeploymentOptions().setWorkerPoolName("coffee-making-pool")
                  .setWorkerPoolSize(100).setInstances(20).setWorker(true));

Stack Trace:

2019-06-19T15:20:37,037 - WARN  - [vert.x-eventloop-thread-7:DefaultChannelPipeline@1188] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.Exception: Wrong message type io.netty.buffer.PooledUnsafeDirectByteBuf
at io.vertx.mqtt.impl.MqttServerConnection.handleMessage(MqttServerConnection.java:182) ~[vertx-mqtt-3.6.3.jar:3.6.3]
at io.vertx.mqtt.impl.MqttServerImpl.lambda$null$3(MqttServerImpl.java:94) ~[vertx-mqtt-3.6.3.jar:3.6.3]
at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225) ~[vertx-core-3.6.3.jar:3.6.3]
at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123) ~[vertx-core-3.6.3.jar:3.6.3]
at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:370) ~[vertx-core-3.6.3.jar:3.6.3]
at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:397) ~[vertx-core-3.6.3.jar:3.6.3]
at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.6.3.jar:3.6.3]
at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:34) ~[vertx-core-3.6.3.jar:3.6.3]
at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[vertx-core-3.6.3.jar:3.6.3]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_162]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_162]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by vietj** [comment]
Can you check with latest version if that still happen ?

**Comment by jmadeira** [comment]
Also with the same issue:
`13:29:02.415 [vert.x-eventloop-thread-0] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoSuchMethodError: 'boolean io.netty.buffer.ByteBuf.isContiguous()'
	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:83)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:274)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)`

**Comment by vietj** [comment]
do you have a reproducer ?

**Comment by vietj** [comment]
it looks like also that this is triggered by a wrong Netty jar files in yoru case : "boolean io.netty.buffer.ByteBuf.isContiguous()"

**Comment by jmadeira** [comment]
> do you have a reproducer ?

Just try a gridsearch and try to check the arbiter URL.
The gridsearch works fine but when I check the URL this error pops up.

**Comment by vietj** [comment]
do you have a project that you can share on github that reproduces the issue ?
