### ISSUE TITLE
 [vert.x-eventloop-thread-11:DefaultChannelPipeline@1188] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

### ISSUE THREAD

**Issue by SivaSamrajS** [vert-x3/vertx-mqtt#137]
While starting with 20 new vertx instances with 20 ports, i am getting below error. Can you help me? 
 
The version i am using is 3.6.2 

`cluster.result().deployVerticle(
          "com.abc.abc",
          new DeploymentOptions().setWorkerPoolName("coffee-making-pool")
              .setWorkerPoolSize(100).setInstances(20).setWorker(true));`   

`java.lang.Exception: Wrong message type io.netty.buffer.PooledUnsafeDirectByteBuf
	at io.vertx.mqtt.impl.MqttServerConnection.handleMessage(MqttServerConnection.java:182) ~[vertx-mqtt-3.6.2.jar:3.6.2]
	at io.vertx.mqtt.impl.MqttServerImpl.lambda$null$3(MqttServerImpl.java:94) ~[vertx-mqtt-3.6.2.jar:3.6.2]
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225) ~[vertx-core-3.6.2.jar:3.6.2]
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123) ~[vertx-core-3.6.2.jar:3.6.2]
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:370) ~[vertx-core-3.6.2.jar:3.6.2]
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:386) ~[vertx-core-3.6.2.jar:3.6.2]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.6.2.jar:3.6.2]
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:34) ~[vertx-core-3.6.2.jar:3.6.2]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[vertx-core-3.6.2.jar:3.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_192]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]`

**Comment by vietj** [comment]
Can you check with latest version if that still happen ?
