### ISSUE TITLE
Intermittent test failure MqttServerWebSocketPermessageDeflateTest

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-mqtt#239]
```
023-06-07T05:08:10.5963841Z testPermessageDeflate(io.vertx.mqtt.test.server.MqttServerWebSocketPermessageDeflateTest)  Time elapsed: 0.064 sec  <<< FAILURE!
2023-06-07T05:08:10.5964419Z java.lang.AssertionError: Test failed
2023-06-07T05:08:10.5975520Z 	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:362)
2023-06-07T05:08:10.5976163Z 	at io.vertx.ext.unit.impl.TestContextImpl.fail(TestContextImpl.java:230)
2023-06-07T05:08:10.5976686Z 	at io.vertx.ext.unit.impl.TestContextImpl.fail(TestContextImpl.java:226)
2023-06-07T05:08:10.5977424Z 	at io.vertx.mqtt.test.server.MqttServerWebSocketPermessageDeflateTest.lambda$testPermessageDeflate$1(MqttServerWebSocketPermessageDeflateTest.java:65)
```

**Comment by tsegismont** [comment]
Outdated
