### ISSUE TITLE
paho client in python  won't work

### ISSUE THREAD

**Issue by Ashye** [vert-x3/vertx-mqtt#81]
when i connect my paho client (in python) to vertx mqtt server, it always raise the same error:
```
java.lang.Exception: Wrong message type
	at io.vertx.mqtt.impl.MqttServerConnection.handleMessage(MqttServerConnection.java:178)
	at io.vertx.mqtt.impl.MqttServerImpl.lambda$null$3(MqttServerImpl.java:89)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:356)
	at io.vertx.core.net.impl.NetServerImpl$2.handleMessage(NetServerImpl.java:445)
	at io.vertx.core.net.impl.NetServerImpl$2.handleMessage(NetServerImpl.java:442)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sammers21** [comment]
@Ashye, can you provide a reproducer and upload it on Github?

**Comment by Ashye** [comment]
i found out the pattern of the issue.
when i deploy a mqtt server with deploy option go with setWorker(true), the problem appearred.
but i don't know why?

**Comment by Sammers21** [comment]
Looking at the error, it seems that message received by mqtt-server is not related to mqtt... 

It is also hard to figure out where is the problem without having a reproducer.

I also don't think that `setWorker(true)` may affect, but who knows.

**Comment by Ashye** [comment]
this is my testing code.
clean project after changing setworker(), 
 

```
class DemoServerVerticle : BaseVerticle(true) {

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            Vertx.factory.vertx().deployVerticle(DemoServerVerticle::class.java.canonicalName,
                    DeploymentOptions().setWorker(true))
        }
    }


    private val mqttServer: MqttServer by lazy { MqttServer.create(vertx) }
    /**
     * client subscription topic list
     */
    private val endpointList = mutableMapOf<String, MutableList<MqttEndpoint>?>()



    override fun start(startFuture: Future<Void>) {

        mqttServer.endpointHandler { endpoint ->
            logger.info("MQTT client [${endpoint.clientIdentifier()}] request to connect, clean session = ${endpoint.isCleanSession()}")

            endpoint.subscribeHandler { subscribe ->
                //handle subscription request
                val qosLevels = mutableListOf<MqttQoS>()
                for (s in subscribe.topicSubscriptions()) {
                    println("Subscription for ${s.topicName()} with QoS ${s.qualityOfService()}")
                    qosLevels.add(s.qualityOfService())

                    val epsOfTopic: MutableList<MqttEndpoint>? = endpointList[s.topicName()]
                    if (epsOfTopic == null) {
                        endpointList[s.topicName()] = mutableListOf(endpoint)
                    }else {
                        epsOfTopic.add(endpoint)
                    }
                }
                endpoint.subscribeAcknowledge(subscribe.messageId(), qosLevels)
            }


            endpoint.publishHandler { message ->
                //receive publish message and message forwarding to client which is interested on this topic
                println("Just received message on [${message.topicName()}] payload [${message.payload()}] with QoS [${message.qosLevel()}]")
                for ((k, v) in endpointList) {
                    if (k == message.topicName()) {
                        v?.forEach {
                            println("forward to : ${it.clientIdentifier()}  ${it.isConnected}")
                            it.publish(k, message.payload(), message.qosLevel(), message.isDup, message.isRetain)
                        }
                    }
                }
            }.publishReleaseHandler { endpoint.publishComplete(it) }


            //make sure publish is over
            endpoint.publishAcknowledgeHandler { println(it) }
                    .publishReceivedHandler { endpoint.publishRelease(it) }
                    .publishCompletionHandler { println(it) }


            endpoint.unsubscribeHandler {
                it.topics().forEach {
                    endpointList[it]?.apply {
                        val deleted = this.filter { it.clientIdentifier() == endpoint.clientIdentifier() }
                        this.removeAll(deleted)
                    }
                }
            }


            endpoint.accept(false)
        }

        mqttServer.listen { ar ->
            if (ar.succeeded()) {
                println("MQTT server started and listening on port ${mqttServer.actualPort()}")
                startFuture.complete()
            }else {
                println("MQTT server error on start${ar.cause()}")
                startFuture.fail(ar.cause())
            }
        }

    }
}
```


```
import paho.mqtt.client as mqtt
from email_sender import sendEmail


def on_connect(client, userdata, flags, rc):
    print("Connected with result code " + str(rc))

    # client.subscribe("test/echo", 0)
    client.subscribe("test/action/send/email", 0)


def on_subscribe(client, userdata, mid, granted_qos):
#     ret = client.publish("test/echo", "this is a test msg", 0, False)
    # print(ret)
    print(userdata, mid, granted_qos)


def on_publish(client, userdata, mid):
    pass


def on_message(client, userdata, msg):
    print(msg.topic + " " + str(msg.payload))
    sendEmail("测试", str(msg.payload, encoding='utf-8'))


client = mqtt.Client("adsfadfadfadf")
client.on_connect = on_connect
client.on_message = on_message
client.on_subscribe = on_subscribe

client.connect("localhost")

client.loop_forever()
```
