### ISSUE TITLE
mqtt2kafka application run a deadlock for a period of time

### ISSUE THREAD

**Issue by lifengchuan2008** [vert-x3/vertx-mqtt#82]
- vertx  3.5.0
- netty  4.1.8.Final

I have a problem，the mqtt to Kafka application receives 51 messages every 2 seconds after 20 hours of deadlock,

#### MqttService
```
  Future<MqttClient> mqttClientFuture = Future.future();
        vertx.executeBlocking(future -> {
            client = MqttClient.create(vertx, options);
            future.complete(client);
        }, res -> {
            mqttClientFuture.complete((MqttClient) res.result());
        });
        mqttClientFuture.setHandler(result -> {
            client.rxConnect(port, host).flatMap(ack -> client.rxSubscribe(topic, 0)).subscribe(sr -> {
                log.debug("mqtt  connected  ,packetId: {}", sr);
            }, error -> {
                log.error("mqtt  connect error: {}", error);
            });
            log.debug("client: {},context: {}", client, vertx.getDelegate().getOrCreateContext());
            client.publishHandler(message -> {
              
                    kafkaService.sendMsg(kafkaTopic, message.payload().toString().getBytes());
                
            });
```

#### KafkaService

```
    @Override
    public void sendMsg(String topic, byte[] msg) {
        producer.rxWrite(KafkaProducerRecord.create(topic, msg)).subscribe(metadata -> {
        });
    }
```

vert.x-worker-thread-4      Mqtt subscribes to tiopic and accepts mqtt messages

 vert.x-eventloop-thread-1    The message received by mqtt is forwarded to Kafka

```
Found one Java-level deadlock:
=============================
"vert.x-worker-thread-4":
  waiting to lock monitor 0x00007efef4020788 (object 0x0000000086964490, a io.vertx.mqtt.impl.MqttClientConnection),
  which is held by "vert.x-eventloop-thread-1"
"vert.x-eventloop-thread-1":
  waiting to lock monitor 0x00007efefc0287d8 (object 0x00000000869644b0, a io.vertx.core.net.impl.NetSocketImpl),
  which is held by "vert.x-worker-thread-4"

Java stack information for the threads listed above:
===================================================
"vert.x-worker-thread-4":
	at io.vertx.mqtt.impl.MqttClientConnection.handleMessage(MqttClientConnection.java:61)
	- waiting to lock <0x0000000086964490> (a io.vertx.mqtt.impl.MqttClientConnection)
	at io.vertx.mqtt.impl.MqttClientImpl.lambda$null$0(MqttClientImpl.java:183)
	at io.vertx.mqtt.impl.MqttClientImpl$$Lambda$118/252270494.handle(Unknown Source)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:356)
	- locked <0x00000000869644b0> (a io.vertx.core.net.impl.NetSocketImpl)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:247)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:244)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
	at io.vertx.core.net.impl.VertxHandler$$Lambda$122/1742062813.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
	at io.vertx.core.impl.ContextImpl$$Lambda$31/1199262943.run(Unknown Source)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:80)
	at io.vertx.core.impl.TaskQueue$$Lambda$28/648680157.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"vert.x-eventloop-thread-1":
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:109)
	- waiting to lock <0x00000000869644b0> (a io.vertx.core.net.impl.NetSocketImpl)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:127)
	at io.vertx.core.net.impl.NetSocketImpl.writeMessage(NetSocketImpl.java:116)
	at io.vertx.mqtt.impl.MqttClientConnection.writeMessage(MqttClientConnection.java:240)
	at io.vertx.mqtt.impl.MqttClientImpl.write(MqttClientImpl.java:642)
	- locked <0x0000000086964490> (a io.vertx.mqtt.impl.MqttClientConnection)
	at io.vertx.mqtt.impl.MqttClientImpl.ping(MqttClientImpl.java:509)
	at io.vertx.mqtt.impl.MqttClientImpl$1.userEventTriggered(MqttClientImpl.java:618)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:371)
	at io.netty.handler.timeout.IdleStateHandler$WriterIdleTimeoutTask.run(IdleStateHandler.java:529)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.
```

**Comment by Sammers21** [comment]
@lifengchuan2008, thank you for reporting this issue. Can you provide an "easy to run and ensure" reproducer?

**Comment by lifengchuan2008** [comment]
@Sammers21 ,thank you for your reply, I have put a reproducer at https://github.com/lifengchuan2008/mqttdeadlock.git

**Comment by Sammers21** [comment]
@lifengchuan2008, good. What is a prerequisite for running this reproducer? Can you add this information to a README file?

**Comment by Sammers21** [comment]
@lifengchuan2008, I also noticed that you are using Google Guice. It is great, but it would be better if you remove all non-related to this issue libraries like Google Guice. So what I am asking for is a minimal reproducible example.

**Comment by Sammers21** [comment]
@lifengchuan2008, any updates on this?

**Comment by Sammers21** [comment]
@lifengchuan2008, I also noticed that you are using netty 4.1.8, while netty 4.1.15.Final should be used with vertx 3.5.0

**Comment by lifengchuan2008** [comment]
@Sammers21, Sorry, because the Spring Festival holiday did not follow this problem, Now we have upgraded the vertx to 3.5.1, netty 4.1.19.Final, and wait for a while to see if there is a problem of deadlocks.Thank you .

**Comment by lifengchuan2008** [comment]
@Sammers21 , Hi, Has been updated,delete  Google Guice ,I tracked it, and after nearly 30 hours, I got the deadlock again.

**Comment by vietj** [comment]
can you try this branch @lifengchuan2008  https://github.com/vert-x3/vertx-mqtt/pull/96 and report wether you still see the deadlocks ?
