### ISSUE TITLE
Deadlock in io.vertx.mqtt.impl.MqttClientConnection

### ISSUE THREAD

**Issue by kirillkh** [vert-x3/vertx-mqtt#92]
Vertx 3.5.1

After several days of running my server that uses vertx-mqtt, it got stuck in a deadlock with the following stack trace. The verticle that runs this client is really simple, it only calls `client.publish` in a single place, nothing else. I'm fairly sure there is no possibility my code is to blame for this deadlock.

Looking at my logs, I found that the other thread that apparently participated in this deadlock was not managed by Vertx, so there is no stack trace available, but I can tell it got locked either when calling `client.subscribe(String, int, Handler)` or waiting the subscription to complete on a *different* instance of MqttClient running in a different verticle.  I was not able to extract the other stack trace, because I was in a rush to restart the server.

Any help would be appreciated.

```
[2018-05-14 11:06:20] [WARNING] io.vertx.core.impl.BlockedThreadChecker: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 5246 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
        at io.vertx.mqtt.impl.MqttClientConnection.handleMessage(MqttClientConnection.java:61)
        at io.vertx.mqtt.impl.MqttClientImpl.lambda$null$0(MqttClientImpl.java:192)
        at io.vertx.mqtt.impl.MqttClientImpl$$Lambda$64/57249380.handle(Unknown Source)
        at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:351)
        at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:242)
        at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:239)
        at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
        at io.vertx.core.net.impl.VertxHandler$$Lambda$71/465081768.run(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.ContextImpl$$Lambda$29/199640888.run(Unknown Source)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by vietj** [comment]
can you make a heap dump and show the full deadlock ? (i;e the two threads deadlocking along with the lock acquisition info).

**Comment by kirillkh** [comment]
I can the next time it happens...

**Comment by vietj** [comment]
it seems similar indeed, but in this case we don't know the other thread of the deadlock

**Comment by vietj** [comment]
I think ideally @Sammers21 we should not own a lock when we write with the client, i.e `io.vertx.mqtt.impl.MqttClientImpl.write(MqttClientImpl.java:642)` should not lock on the client

**Comment by vietj** [comment]
I think @Sammers21 that we change the code in MQTT to use the NetSocket as lock and not lock on the MqttClientConnection.

**Comment by vietj** [comment]
can you try this branch @kirillkh https://github.com/vert-x3/vertx-mqtt/pull/96 and report wether you still see the deadlocks ?
